/** Core ReAct loop for fixture-scoped specialist agents with evidence and research deduplication. */
import { dispatchTool } from '../tools.js';
import type { ReActStep } from '../react-engine.js';
import { mistralPool } from '../mistral-pool.js';
import { saveCheckpoint, loadCheckpoint, clearCheckpoint } from '../checkpoint.js';
import { getResearch, setResearch } from '../research-cache.js';

export interface SubAgentResult {agentName:string;success:boolean;partial?:boolean;data:Record<string,unknown>;steps:ReActStep[];rawOutput:string;error?:string;toolErrors?:string[];}
type MsgRole='user'|'assistant'|'system'; interface Msg{role:MsgRole;content:string;}
const CHANGE_APPROACH_HINTS:Record<string,string>={scrape:'Switch from scrape to fetch_url, or use serper_search / talordata_search. Never re-scrape the same blocked URL.',fetch_url:'Switch from fetch_url to search or a different URL.',web_search:'Try serper_search/talordata_search or reformulate the query.',talordata_search:'Try serper_search or a new source/query.',serper_search:'Try talordata_search or a direct sports-data URL.',allsports_fixtures:'Try fetch_matches_today or serper_search.',allsports_livescore:'Try scrape_flashscore or fetch_matches_today.'};
const INVALID_TOOL_NAME_PATTERNS=[/excluded\s+from\s+analysis/i,/waiting/i,/proceeding/i,/final\s+json/i,/^fallback$/i,/action\s+input/i];
function buildChangeApproachMessage(n:number,failed:string[],sources:string[],remaining:number){const hints=[...new Set(failed)].map(t=>CHANGE_APPROACH_HINTS[t]||'Try a completely different source and tool.').join(' ');return`⚠️ MANDATORY STRATEGY CHANGE (${n} consecutive failures):\nFAILED SOURCES — do NOT retry: ${sources.slice(-8).join(' | ')}\n${hints}\nYou have ${remaining} iteration(s) left. Each must use a NEW source/query. If data cannot be verified, output SUBAGENT_DONE with unavailable fields.`;}
function extractTargetFixture(task:string):string|null{for(const pattern of[/(?:for|about)\s*:\s*([^\n]+?)(?:\s*\([^\n]+\))?(?:\n|$)/i,/fixture\s*=\s*([^\n]+)/i,/\[([^\]]+\s+vs\.?\s+[^\]]+)\]/i]){const v=task.match(pattern)?.[1]?.trim();if(v&&/\s+(?:vs\.?|v\.?)\s+/i.test(v))return v;}return null;}
function normalizeFixture(value:string){return value.toLowerCase().replace(/\s+/g,' ').replace(/\s*(?:vs\.?|v\.?)\s*/g,' vs ').trim();}
function isolateFixtureContext(task:string,targetFixture:string|null){if(!targetFixture)return task;const target=normalizeFixture(targetFixture);const marker=/===\s*([^=\n]+?\s+vs\.?\s+[^=\n]+?)\s*===/gi;const matches=[...task.matchAll(marker)];if(!matches.length)return task;const sections:string[]=[];for(let i=0;i<matches.length;i++){const start=matches[i].index??0,end=i+1<matches.length?(matches[i+1].index??task.length):task.length;if(normalizeFixture(matches[i][1])===target)sections.push(task.slice(start,end));}if(!sections.length)return`${task.slice(0,matches[0].index??task.length).trim()}\n\n=== FIXTURE-ISOLATED PRIOR CONTEXT ===\nNo matching prior result block.`;return`${task.slice(0,matches[0].index??0).trim()}\n\n=== FIXTURE-ISOLATED PRIOR CONTEXT ===\n${sections.join('\n')}`;}
function containsPlaceholderUrl(input:Record<string,unknown>){return[input.url,input.query].filter(Boolean).map(String).some(v=>/123456|placeholder|example\.com|<[^>]+>|\.{3,}|\/goto\?url=/i.test(v));}
function qualityGuardInstruction(agentName:string,fixture:string|null){return`QUALITY GATE FOR ${agentName.toUpperCase()}:${fixture?` The ONLY fixture you may research is: ${fixture}.`:''}\n- Never transfer facts from another fixture.\n- Never invent missing values.\n- Never use generic averages as fixture-specific evidence.\n- Never use placeholder URLs or guessed IDs.\n- Every factual field must be traceable to a tool observation or marked unavailable.`;}
async function cachedDispatch(toolName:string,input:Record<string,unknown>,fixture:string|null){const cacheable=new Set(['serper_search','talordata_search','web_search','fetch_url','scrape','scrape_flashscore','fetch_matches_today','allsports_fixtures']);if(!fixture||!cacheable.has(toolName))return dispatchTool(toolName,input);const sourceKey=JSON.stringify(input);const cached=getResearch<any>(fixture,`${toolName}:${sourceKey}`);if(cached)return cached;const result=await dispatchTool(toolName,input);if(result.success&&!result.blocked)setResearch(fixture,`${toolName}:${sourceKey}`,result,toolName);return result;}

export async function runSubAgent(opts:{agentName:string;systemPrompt:string;task:string;sessionId?:string;maxIterations?:number;prefix?:string;onStep:(step:ReActStep)=>void;tier?:number;}):Promise<SubAgentResult>{const{agentName,systemPrompt,task,sessionId='default',maxIterations=8,prefix='',onStep}=opts;const targetFixture=extractTargetFixture(task),isolatedTask=isolateFixtureContext(task,targetFixture),guardedSystemPrompt=`${systemPrompt}\n\n${qualityGuardInstruction(agentName,targetFixture)}`;const steps:ReActStep[]=[];const toolErrors:string[]=[];const now=()=>new Date().toISOString();const triedHashes=new Set<string>();const emit=(step:ReActStep)=>{const s={...step,content:prefix?`[${prefix}] ${step.content}`:step.content,timestamp:now()};steps.push(s);onStep(s);return s;};
 const existing=await loadCheckpoint(sessionId,agentName);let messages:Msg[],startIteration:number,rawOutput:string,accumulatedData:Record<string,unknown>;if(existing&&existing.iteration<maxIterations-1){emit({type:'status',content:`Resuming from checkpoint @ iteration ${existing.iteration}`});messages=existing.messages as Msg[];startIteration=existing.iteration;rawOutput=existing.rawOutput;accumulatedData=existing.accumulatedData||{};}else{messages=[{role:'system',content:guardedSystemPrompt},{role:'user',content:isolatedTask}];startIteration=0;rawOutput='';accumulatedData={};}
 let consecutiveErrors=0;const triedSources:string[]=[];const failedToolNames:string[]=[];
 try{for(let i=startIteration;i<maxIterations;i++){const resp=await mistralPool.call(client=>client.chat.complete({model:'mistral-large-latest',messages:messages as any,temperature:.1,maxTokens:2500}));const content=resp.choices?.[0]?.message?.content||'';if(typeof content!=='string'||!content.trim())break;rawOutput=content;if(content.includes('SUBAGENT_DONE:')){rawOutput=content.substring(content.indexOf('SUBAGENT_DONE:')+14).trim();emit({type:'synthesis',content:`${agentName} complete`,iteration:i+1});break;}const thoughtM=content.match(/Thought:\s*([\s\S]*?)(?=Action:|SUBAGENT_DONE:|$)/i),actionM=content.match(/Action:\s*([^\n]+)/i),inputM=content.match(/Action Input:\s*([\s\S]*?)(?=Thought:|Action:|SUBAGENT_DONE:|$)/i);const thought=thoughtM?.[1]?.trim()||'',toolName=(actionM?.[1]?.trim()||'').replace(/^[*`]+|[*`]+$/g,'').trim(),rawInput=inputM?.[1]?.trim()||'{}';if(thought)emit({type:'thought',content:thought,iteration:i+1});if(!toolName){emit({type:'synthesis',content:`${agentName} complete`,iteration:i+1});break;}if(INVALID_TOOL_NAME_PATTERNS.some(p=>p.test(toolName))){toolErrors.push(`${toolName}: invalid action`);emit({type:'error',content:`Ignored invalid tool action text: ${toolName}`,iteration:i+1});break;}
 let toolInput:Record<string,unknown>={};try{const clean=rawInput.replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/i,'').trim();toolInput=JSON.parse(clean);}catch{const u=rawInput.match(/"url"\s*:\s*"([^"]+)"/),q=rawInput.match(/"query"\s*:\s*"([^"]+)"/),s=rawInput.match(/"selector"\s*:\s*"([^"]+)"/);if(u)toolInput.url=u[1];if(q)toolInput.query=q[1];if(s)toolInput.selector=s[1];if(!Object.keys(toolInput).length)toolInput.query=rawInput.replace(/[{}\"]/g,'').trim();}
 if(containsPlaceholderUrl(toolInput)){toolErrors.push(`${toolName}: placeholder source rejected`);emit({type:'error',content:`Rejected placeholder/synthetic source`,iteration:i+1});continue;}
 const sourceKey=String(toolInput.url||toolInput.query||'').substring(0,150),callHash=`${toolName}:${sourceKey}`;if(triedHashes.has(callHash)){emit({type:'status',content:`Skipping duplicate call: ${callHash.substring(0,80)}`,iteration:i+1});messages.push({role:'user',content:`You already tried ${sourceKey}; use a different source.`});continue;}triedHashes.add(callHash);if(sourceKey)triedSources.push(sourceKey);emit({type:'action',content:`→ ${toolName}`,toolName,toolInput,iteration:i+1});const result=await cachedDispatch(toolName,toolInput,targetFixture);let obs:string;if(result.success&&!result.blocked){obs=(result.data||'Empty result').substring(0,6000);consecutiveErrors=0;failedToolNames.length=0;}else{consecutiveErrors++;failedToolNames.push(toolName);toolErrors.push(`${toolName}: ${result.error||'blocked'}`);obs=result.blocked?`BLOCKED: anti-bot wall on ${sourceKey}`:`ERROR: ${result.error||'unknown'} source=${sourceKey}`;}emit({type:'observation',content:obs.substring(0,800)+(obs.length>800?'…':''),iteration:i+1});messages.push({role:'assistant',content},{role:'user',content:`Observation: ${obs}`});if(consecutiveErrors>=2){const remaining=maxIterations-i-1;if(consecutiveErrors>=3||remaining<=1)messages.push({role:'user',content:'Stop using tools and output SUBAGENT_DONE with verified data only.'});else messages.push({role:'user',content:buildChangeApproachMessage(consecutiveErrors,failedToolNames,triedSources,remaining)});}await saveCheckpoint({sessionId,agentName,messages,iteration:i+1,steps:[...steps],rawOutput,accumulatedData,savedAt:Date.now(),version:5});}
 if(!rawOutput.includes('SUBAGENT_DONE:')&&!/\{[\s\S]+\}/.test(rawOutput)&&messages.length>2){try{messages.push({role:'user',content:'Iteration budget exhausted. Output SUBAGENT_DONE followed by JSON only; never invent.'});const wrap=await mistralPool.call(c=>c.chat.complete({model:'mistral-large-latest',messages:messages as any,temperature:0,maxTokens:1500}));const c=wrap.choices?.[0]?.message?.content;if(typeof c==='string'&&c){rawOutput=c.includes('SUBAGENT_DONE:')?c.substring(c.indexOf('SUBAGENT_DONE:')+14).trim():c;}}catch{}}
 let data:Record<string,unknown>={};try{const m=rawOutput.match(/```json\s*([\s\S]+?)\s*```/)||rawOutput.match(/(\{[\s\S]+\})/);if(m)data=JSON.parse(m[1]);}catch{data={raw:rawOutput};}const merged={...accumulatedData,...data};await clearCheckpoint(sessionId,agentName);return{agentName,success:true,partial:toolErrors.length>0&&Object.keys(data).length>0,data:merged,steps,rawOutput,toolErrors:toolErrors.length?toolErrors:undefined};
 }catch(err){const msg=err instanceof Error?err.message:String(err);emit({type:'error',content:`${agentName} error: ${msg}`});return{agentName,success:false,data:{},steps,rawOutput:'',error:msg,toolErrors};}}
