export const PLATFORMS = {
    'football.com': {
        id: 'football.com',
        name: 'Football.com',
        baseUrl: 'https://www.football.com',
        loginUrl: 'https://www.football.com/login',
        searchable: true,
        selectors: {
            usernameInput: 'input[type="email"], input[type="text"], input[name="username"], input[name="email"]',
            passwordInput: 'input[type="password"]',
            loginButton: 'button[type="submit"], .login-btn, .submit-btn',
            searchBox: 'input[placeholder*="search" i], .search-input input',
            betslipStakeInput: 'input[placeholder*="stake" i], input[placeholder*="amount" i], .stake-input, input[type="number"]',
            betslipConfirmButton: 'button[type="submit"], .place-bet-btn, .confirm-bet',
            oddsDisplay: '.odds, .price, [class*="odds"]',
            confirmationMsg: '.success, .bet-confirmed, [class*="success"]',
            cookieBanner: '.accept-cookies, #cookie-accept',
        },
    },
    sportybet: {
        id: 'sportybet',
        name: 'SportyBet',
        baseUrl: 'https://www.sportybet.com',
        loginUrl: 'https://www.sportybet.com/ng/#/login',
        searchable: true,
        selectors: {
            usernameInput: 'input[type="tel"], input[name="phone"], input[placeholder*="phone" i]',
            passwordInput: 'input[type="password"]',
            loginButton: 'button[type="submit"], .login-btn, button:contains("Login"), button:contains("Sign in")',
            searchBox: 'input[placeholder*="search" i], .search-input input',
            betslipStakeInput: 'input[placeholder*="stake" i], .stake-input input, input[type="number"]',
            betslipConfirmButton: '.bet-slip-btn, button:contains("Place Bet"), .place-bet-btn',
            oddsDisplay: '.odds-value, .price, [class*="odds"]',
            confirmationMsg: '.success-msg, .bet-success, [class*="success"]',
            cookieBanner: '[class*="cookie"] button, .accept-cookies',
        },
    },
    bet365: {
        id: 'bet365',
        name: 'Bet365',
        baseUrl: 'https://www.bet365.com',
        loginUrl: 'https://www.bet365.com/#/HO/',
        searchable: false,
        selectors: {
            usernameInput: 'input[name="username"], .hm-login__username input',
            passwordInput: 'input[type="password"]',
            loginButton: '.hm-login__login-btn, button[type="submit"]',
            betslipStakeInput: '.bs3-Betslip_StakeInput, input[aria-label*="Stake"]',
            betslipConfirmButton: '.bs3-PlaceBets_Btn, .bs3-Betslip_SingleBetslip button[type="submit"]',
            oddsDisplay: '.gl-Participant_Odds, .bs3-Selection_Odds',
            confirmationMsg: '.bs3-ReceiptBetslip, .bs3-ConfirmationMessage',
            cookieBanner: '#onetrust-accept-btn-handler, .CookiePolicy_Accept',
        },
    },
    '1xbet': {
        id: '1xbet',
        name: '1xBet',
        baseUrl: 'https://1xbet.com',
        loginUrl: 'https://1xbet.com/en/login',
        searchable: true,
        selectors: {
            usernameInput: '#loginform input[type="text"], input[name="login"]',
            passwordInput: 'input[type="password"]',
            loginButton: '.auth_form_row button[type="submit"], .enter_btn',
            searchBox: '.search-form input, input[placeholder*="search" i]',
            betslipStakeInput: '.bet-area input[type="text"], .coupon_input',
            betslipConfirmButton: '.btn-accept, .betslip-btn-make-bet',
            oddsDisplay: '.odd, .bet_koef',
            confirmationMsg: '.message_success, .bet_accepted',
            cookieBanner: '.cookie-btn, #bx_3966949_accept',
        },
    },
    betway: {
        id: 'betway',
        name: 'Betway',
        baseUrl: 'https://betway.com',
        loginUrl: 'https://betway.com/en/login',
        searchable: true,
        selectors: {
            usernameInput: '#username, input[name="username"]',
            passwordInput: '#password, input[name="password"]',
            loginButton: '.button--login, button[data-testid="login-btn"]',
            searchBox: '.search-bar input',
            betslipStakeInput: '.bet-amount-input, input[placeholder*="amount" i]',
            betslipConfirmButton: '.place-bet-btn, button[data-testid="place-bet"]',
            oddsDisplay: '.bet-odd',
            confirmationMsg: '.bet-confirmation',
            cookieBanner: '#onetrust-accept-btn-handler',
        },
    },
    betika: {
        id: 'betika',
        name: 'Betika',
        baseUrl: 'https://www.betika.com',
        loginUrl: 'https://www.betika.com/en-ke/',
        searchable: true,
        selectors: {
            usernameInput: 'input[placeholder*="phone" i], input[type="tel"]',
            passwordInput: 'input[type="password"]',
            loginButton: 'button[type="submit"], .loginBtn',
            searchBox: 'input[placeholder*="search" i]',
            betslipStakeInput: 'input[placeholder*="stake" i], .amount-input input',
            betslipConfirmButton: '.place-bet, button:contains("Place Bet")',
            oddsDisplay: '.odds',
            confirmationMsg: '.bet-placed, .success',
            cookieBanner: '.accept-all-cookies',
        },
    },
    parimatch: {
        id: 'parimatch',
        name: 'Parimatch',
        baseUrl: 'https://parimatch.com',
        loginUrl: 'https://parimatch.com/en/login',
        searchable: false,
        selectors: {
            usernameInput: 'input[type="text"]',
            passwordInput: 'input[type="password"]',
            loginButton: 'button[type="submit"]',
            betslipStakeInput: 'input[name="amount"]',
            betslipConfirmButton: 'button[type="submit"]',
            oddsDisplay: '.odd',
            confirmationMsg: '.success',
            cookieBanner: '.cookie-btn',
        },
    },
    melbet: {
        id: 'melbet',
        name: 'Melbet',
        baseUrl: 'https://melbet.com',
        loginUrl: 'https://melbet.com/en/login',
        searchable: false,
        selectors: {
            usernameInput: 'input[type="text"]',
            passwordInput: 'input[type="password"]',
            loginButton: 'button[type="submit"]',
            betslipStakeInput: 'input[class*="stake"]',
            betslipConfirmButton: 'button[class*="confirm"]',
            oddsDisplay: '.odd',
            confirmationMsg: '.success',
            cookieBanner: '.cookie-btn',
        },
    },
    betwinner: {
        id: 'betwinner',
        name: 'Betwinner',
        baseUrl: 'https://betwinner.com',
        loginUrl: 'https://betwinner.com/en/login',
        searchable: false,
        selectors: {
            usernameInput: 'input[type="text"]',
            passwordInput: 'input[type="password"]',
            loginButton: 'button[type="submit"]',
            betslipStakeInput: 'input[name="amount"]',
            betslipConfirmButton: 'button[type="submit"]',
            oddsDisplay: '.odd',
            confirmationMsg: '.success',
            cookieBanner: '.cookie-btn',
        },
    },
};
export function getPlatform(id) {
    return PLATFORMS[id] || null;
}
export function listPlatforms() {
    return Object.values(PLATFORMS).map(p => ({ id: p.id, name: p.name }));
}
//# sourceMappingURL=platforms.js.map