import { query } from '../db/index.js';

const AIRTABLE_API_KEY = process.env.AIRTABLE_API_KEY || '';
const AIRTABLE_BASE_ID_ENV = process.env.AIRTABLE_BASE_ID || '';
const AIRTABLE_WORKSPACE_ID = process.env.AIRTABLE_WORKSPACE_ID || '';
const AIRTABLE_API = 'https://api.airtable.com/v0';

const safeNumber = (n:any):number|undefined => typeof n === 'number' && !isNaN(n) ? n : undefined;
const toISO = (d:any):string|undefined => { if (!d) return undefined; const date=new Date(d); return isNaN(date.getTime()) ? undefined : date.toISOString(); };
const cleanFields = (obj:Record<string,any>) => Object.fromEntries(Object.entries(obj).filter(([,v])=>v!==undefined&&v!==null&&!(typeof v==='number'&&isNaN(v))));
const DATE_TIME_OPTIONS = { dateFormat:{name:'iso'}, timeFormat:{name:'24hour'}, timeZone:'utc' };
const CHECKBOX_OPTIONS = { color:'greenBright', icon:'check' };

const PREDICTION_BASE_FIELDS = [
  {name:'Prediction ID',type:'singleLineText'},{name:'Fixture',type:'singleLineText'},{name:'Sport',type:'singleLineText'},{name:'League',type:'singleLineText'},{name:'Market',type:'singleLineText'},{name:'Selection',type:'singleLineText'},{name:'Decision Type',type:'singleLineText'},{name:'Validation Status',type:'singleLineText'},{name:'Betting Status',type:'singleLineText'},
  {name:'Kickoff Time',type:'dateTime',options:DATE_TIME_OPTIONS},{name:'Predicted Prob %',type:'number',options:{precision:2}},{name:'Implied Prob %',type:'number',options:{precision:2}},{name:'EV %',type:'number',options:{precision:4}},{name:'Confidence %',type:'number',options:{precision:2}},{name:'Star Rating',type:'number',options:{precision:0}},{name:'Recommended Odds',type:'number',options:{precision:3}},{name:'Data Completeness',type:'number',options:{precision:1}},{name:'Is Value Bet',type:'checkbox',options:CHECKBOX_OPTIONS},{name:'Recommended Stake',type:'singleLineText'},
  {name:'Market Score',type:'number',options:{precision:4}},{name:'Form Score',type:'number',options:{precision:4}},{name:'Injury Score',type:'number',options:{precision:4}},{name:'Sentiment Score',type:'number',options:{precision:4}},{name:'MC Home Win %',type:'number',options:{precision:4}},{name:'MC Draw %',type:'number',options:{precision:4}},{name:'MC Away Win %',type:'number',options:{precision:4}},{name:'MC Std Dev',type:'number',options:{precision:4}},{name:'Is Combo',type:'checkbox',options:CHECKBOX_OPTIONS},{name:'Combo Leg IDs',type:'singleLineText'},{name:'Goal Statement',type:'multilineText'},{name:'Created At',type:'dateTime',options:DATE_TIME_OPTIONS}
];

const RESULT_FIELDS = [
  {name:'Prediction ID',type:'singleLineText'},{name:'Fixture',type:'singleLineText'},{name:'Market',type:'singleLineText'},{name:'Selection',type:'singleLineText'},{name:'Actual Outcome',type:'singleLineText'},
  {name:'Result',type:'singleSelect',options:{choices:[{name:'pending'},{name:'won'},{name:'lost'},{name:'void'},{name:'half_win'},{name:'half_loss'},{name:'push'},{name:'manual_review'}]}},{name:'Void Reason',type:'singleLineText'},{name:'Settled At',type:'dateTime',options:DATE_TIME_OPTIONS},{name:'Final Score',type:'singleLineText'},{name:'ROI',type:'number',options:{precision:4}}
];

type AirtableInit={baseId:string;tables:Record<string,string>;fields:Record<string,Set<string>>};
let cache:AirtableInit|null=null;

async function airtableFetch(path:string,options:RequestInit={}){const res=await fetch(`${AIRTABLE_API}${path}`,{...options,headers:{Authorization:`Bearer ${AIRTABLE_API_KEY}`,'Content-Type':'application/json',...options.headers}});if(!res.ok){const text=await res.text();console.error('[Airtable ERROR]',res.status,text);throw new Error(`Airtable ${res.status}: ${text}`);}return res.json();}
async function ensureRegistry(){await query(`CREATE TABLE IF NOT EXISTS airtable_registry (id INT AUTO_INCREMENT PRIMARY KEY,base_id VARCHAR(100),table_name VARCHAR(100),table_id VARCHAR(100),UNIQUE KEY uniq (base_id,table_name))`);}
async function register(baseId:string,name:string,id:string){await query(`INSERT INTO airtable_registry (base_id,table_name,table_id) VALUES (?,?,?) ON DUPLICATE KEY UPDATE table_id=VALUES(table_id)`,[baseId,name,id]);}
async function createBase(){if(!AIRTABLE_WORKSPACE_ID)throw new Error('Missing AIRTABLE_WORKSPACE_ID');const data=await airtableFetch('/meta/bases',{method:'POST',body:JSON.stringify({name:'Odessyus Quant Punter',workspaceId:AIRTABLE_WORKSPACE_ID})});return data.id as string;}
async function createTable(baseId:string,name:string,fields:any[]){try{return await airtableFetch(`/meta/bases/${baseId}/tables`,{method:'POST',body:JSON.stringify({name,fields})});}catch(error){console.warn(`[Airtable] Could not create table ${name}:`,error instanceof Error?error.message:String(error));return null;}}
async function ensurePredictionFields(baseId:string,tableId:string,existing:Set<string>){for(const field of PREDICTION_BASE_FIELDS){if(existing.has(field.name))continue;try{await airtableFetch(`/meta/bases/${baseId}/tables/${tableId}/fields`,{method:'POST',body:JSON.stringify(field)});existing.add(field.name);}catch(error){console.warn(`[Airtable] Could not create field ${field.name}:`,error instanceof Error?error.message:String(error));}}}
export async function initAirtable():Promise<AirtableInit|null>{if(!AIRTABLE_API_KEY){console.warn('[Airtable] Missing API key. Skipping.');return null;}await ensureRegistry();let baseId=AIRTABLE_BASE_ID_ENV||'';if(!baseId){const rows=await query<any[]>('SELECT base_id FROM airtable_registry LIMIT 1');if(rows.length)baseId=rows[0].base_id;}if(!baseId){console.log('[Airtable] Creating new base...');baseId=await createBase();}const schema=await airtableFetch(`/meta/bases/${baseId}/tables`);const rawTables:any[]=schema.tables||[];if(!rawTables.some(t=>t.name==='Predictions')){const created=await createTable(baseId,'Predictions',PREDICTION_BASE_FIELDS);if(created)rawTables.push(created);}if(!rawTables.some(t=>t.name==='Results')){const created=await createTable(baseId,'Results',RESULT_FIELDS);if(created)rawTables.push(created);}const tables:Record<string,string>={},fields:Record<string,Set<string>>={};for(const table of rawTables){if(!table?.name||!table?.id)continue;tables[table.name]=table.id;fields[table.name]=new Set((table.fields||[]).map((f:any)=>f.name));await register(baseId,table.name,table.id);}if(tables.Predictions)await ensurePredictionFields(baseId,tables.Predictions,fields.Predictions||new Set());if(tables.Results) { const available=fields.Results||new Set<string>(); for(const field of RESULT_FIELDS){if(available.has(field.name))continue;try{await airtableFetch(`/meta/bases/${baseId}/tables/${tables.Results}/fields`,{method:'POST',body:JSON.stringify(field)});available.add(field.name);}catch(error){console.warn(`[Airtable] Could not create Results field ${field.name}:`,error instanceof Error?error.message:String(error));}} fields.Results=available; } cache={baseId,tables,fields};return cache;}
function parseDecisionPayload(goalStatement:any){if(typeof goalStatement!=='string')return null;try{const parsed=JSON.parse(goalStatement);return parsed?.primaryBet?parsed:null;}catch{return null;}}
function predictionFields(data:any,decision:any,decisionType:string,available:Set<string>,id:string){const market=decision?.market||data.market;const selection=decision?.selection||data.selection||'';const probabilityPct=Number.isFinite(Number(decision?.probability_pct))?Number(decision.probability_pct):safeNumber(data.predictedProb*100);const odds=Number.isFinite(Number(decision?.odds))?Number(decision.odds):safeNumber(data.recommendedOdds);const ev=Number.isFinite(Number(decision?.ev_pct))?Number(decision.ev_pct):safeNumber(data.evPct*100);const validation=decision?.validation||(data.isValueBet?'VALIDATED':'UNVERIFIED');const status=decision?.status||(data.isValueBet?'BET':'SKIP');const confidence=Number.isFinite(Number(decision?.confidence_pct))?Number(decision.confidence_pct):safeNumber(data.dataCompleteness);const base:Record<string,any>={'Prediction ID':id,Fixture:data.fixture,Sport:data.sport,League:data.league,Market:market,Selection:selection,'Decision Type':decisionType,'Validation Status':validation,'Betting Status':status,'Kickoff Time':toISO(data.kickoffTime),'Predicted Prob %':probabilityPct,'Implied Prob %':odds&&odds>1?100/odds:safeNumber(data.impliedProb*100),'EV %':ev,'Confidence %':confidence,'Star Rating':safeNumber(data.starRating),'Recommended Odds':odds,'Data Completeness':safeNumber(data.dataCompleteness),'Is Value Bet':status==='BET'||data.isValueBet===true,'Recommended Stake':decisionType==='PRIMARY_BET'&&status==='BET'?data.recommendedStake:'WATCHLIST','Market Score':safeNumber(data.categoryProbabilities?.market),'Form Score':safeNumber(data.categoryProbabilities?.form),'Injury Score':safeNumber(data.categoryProbabilities?.injury),'Sentiment Score':safeNumber(data.categoryProbabilities?.sentiment),'MC Home Win %':safeNumber(data.monteCarlo?.home),'MC Draw %':safeNumber(data.monteCarlo?.draw),'MC Away Win %':safeNumber(data.monteCarlo?.away),'MC Std Dev':safeNumber(data.monteCarlo?.stdDev),'Is Combo':data.isCombo,'Combo Leg IDs':data.comboLegIds,'Goal Statement':decision?.reason||data.goalStatement,'Created At':new Date().toISOString()};const out:Record<string,any>={};for(const[k,v]of Object.entries(cleanFields(base))){if(available.has(k)||['Prediction ID','Fixture','Sport','League','Market','Selection','Decision Type','Validation Status','Betting Status','Kickoff Time','Predicted Prob %','Implied Prob %','EV %','Confidence %','Star Rating','Recommended Odds','Data Completeness','Is Value Bet','Recommended Stake','Market Score','Form Score','Injury Score','Sentiment Score','MC Home Win %','MC Draw %','MC Away Win %','MC Std Dev','Is Combo','Combo Leg IDs','Goal Statement','Created At'].includes(k))out[k]=v;}return out;}
export async function logPrediction(data:any){const init=cache||await initAirtable();if(!init)return;const tableId=init.tables.Predictions;if(!tableId){console.error('Missing Predictions table ID');return;}const available=init.fields.Predictions||new Set<string>();const payload=parseDecisionPayload(data.goalStatement);const records:Array<{fields:Record<string,any>}>=[];if(payload?.primaryBet){records.push({fields:predictionFields(data,payload.primaryBet,'PRIMARY_BET',available,`${data.predictionId}-primary`)});for(let i=0;i<(payload.alternativePicks||[]).length;i++)records.push({fields:predictionFields(data,payload.alternativePicks[i],'ALTERNATIVE',available,`${data.predictionId}-alt-${i+1}`)});}else records.push({fields:predictionFields(data,null,'LEGACY',available,data.predictionId)});if(records.length)await airtableFetch(`/${init.baseId}/${tableId}`,{method:'POST',body:JSON.stringify({records})});}
export async function logResult(data:any){const init=cache||await initAirtable();if(!init)return;const tableId=init.tables.Results;if(!tableId){console.error('Missing Results table ID');return;}const fields=cleanFields({'Prediction ID':data.predictionId,Fixture:data.fixture,Market:data.market,Selection:data.selection||'', 'Actual Outcome':data.actualOutcome,Result:data.result,'Void Reason':data.voidReason,'Final Score':data.finalScore,ROI:safeNumber(data.roi),'Settled At':new Date().toISOString()});await airtableFetch(`/${init.baseId}/${tableId}`,{method:'POST',body:JSON.stringify({records:[{fields}]})});}
