import { query } from '../db/index.js';
export interface BacktestReport{market:string;samples:number;testSamples:number;folds:number;modelBrier:number;marketBrier:number;modelLogLoss:number;marketLogLoss:number;roi:number|null;avgClv:number|null;roiCi95:[number,number]|null;clvBeatPct:number|null;edgePValue:number|null;validated:boolean;reason:string;}
const clamp=(x:number)=>Math.max(.001,Math.min(.999,x));
const ll=(p:number,y:number)=>-(y*Math.log(clamp(p))+(1-y)*Math.log(1-clamp(p)));
function rng(seed:number){let x=seed>>>0;return()=>{x^=x<<13;x^=x>>>17;return(x>>>0)/4294967296;};}
function boot(a:number[],seed:number):[number,number]|null{if(!a.length)return null;const r=rng(seed),m:number[]=[];for(let b=0;b<2000;b++){let s=0;for(let i=0;i<a.length;i++)s+=a[Math.floor(r()*a.length)];m.push(s/a.length);}m.sort((x,y)=>x-y);return[m[Math.floor(m.length*.025)],m[Math.floor(m.length*.975)]];}
function comb(n:number,k:number){let r=1;for(let i=1;i<=k;i++)r=r*(n-k+i)/i;return r;}
function signP(a:number[]){const x=a.filter(v=>v!==0),n=x.length;if(!n)return null;const k=x.filter(v=>v>0).length;let q=0;for(let i=0;i<=Math.min(k,n-k);i++)q+=comb(n,i)/2**n;return Math.min(1,2*q);}
function evaluate(rows:Record<string,unknown>[]){const y=(r:Record<string,unknown>)=>r.status==='won'?1:0;const mp=(r:Record<string,unknown>)=>Number(r.probability)/100;const qp=(r:Record<string,unknown>)=>Number(r.recommended_odds)>1?1/Number(r.recommended_odds):.5;const mb=rows.reduce((s,r)=>s+(mp(r)-y(r))**2,0)/rows.length,bb=rows.reduce((s,r)=>s+(qp(r)-y(r))**2,0)/rows.length,ml=rows.reduce((s,r)=>s+ll(mp(r),y(r)),0)/rows.length,bl=rows.reduce((s,r)=>s+ll(qp(r),y(r)),0)/rows.length;return{mb,bb,ml,bl};}
export async function backtestMarket(market:string):Promise<BacktestReport>{
 const rows=await query<Record<string,unknown>[]>(`SELECT probability,recommended_odds,status,roi,clv_achieved FROM predictions WHERE LOWER(TRIM(prediction_market))=LOWER(TRIM(?)) AND status IN ('won','lost') ORDER BY created_at ASC`,[market]);
 const n=rows.length;const minTest=Number(process.env.BACKTEST_MIN_TEST_SAMPLES||20);if(n<minTest*2)return{market,samples:n,testSamples:Math.floor(n*.3),folds:0,modelBrier:0,marketBrier:0,modelLogLoss:0,marketLogLoss:0,roi:null,avgClv:null,roiCi95:null,clvBeatPct:null,edgePValue:null,validated:false,reason:'Insufficient chronological data for walk-forward testing.'};
 const folds=Math.min(5,Math.max(2,Math.floor(n/minTest)));let totalWeight=0,mb=0,bb=0,ml=0,bl=0;const allRoi:number[]=[];const allClv:number[]=[];
 for(let f=1;f<=folds;f++){const trainEnd=Math.floor(n*(0.5+0.45*(f/folds)));const testStart=Math.max(0,trainEnd-minTest);const test=rows.slice(testStart,Math.min(n,trainEnd));if(test.length<minTest)continue;const m=evaluate(test);const w=test.length;totalWeight+=w;mb+=m.mb*w;bb+=m.bb*w;ml+=m.ml*w;bl+=m.bl*w;for(const r of test){if(r.roi!=null)allRoi.push(Number(r.roi));if(r.clv_achieved!=null)allClv.push(Number(r.clv_achieved));}}
 const testSamples=totalWeight;const roi=allRoi.length?allRoi.reduce((s,x)=>s+x,0)/allRoi.length:null,avgClv=allClv.length?allClv.reduce((s,x)=>s+x,0)/allClv.length:null,ci=boot(allRoi,market.length*97+11),beat=allClv.length?allClv.filter(x=>x>0).length/allClv.length:null,p=signP(allRoi);const modelBrier=mb/(totalWeight||1),marketBrier=bb/(totalWeight||1),modelLogLoss=ml/(totalWeight||1),marketLogLoss=bl/(totalWeight||1);const validated=folds>=3&&modelBrier<=marketBrier&&modelLogLoss<=marketLogLoss&&(roi??-1)>0&&(ci?ci[0]>0:false)&&(avgClv??-1)>0&&(p??1)<.05;return{market,samples:n,testSamples,folds,modelBrier,marketBrier,modelLogLoss,marketLogLoss,roi,avgClv,roiCi95:ci,clvBeatPct:beat,edgePValue:p,validated,reason:validated?'PASS: walk-forward holdouts show better probabilistic quality plus positive, statistically supported edge.':'FAIL: walk-forward evidence does not establish a durable positive edge.'};}
export async function backtestAll(){const ms=await query<Record<string,unknown>[]>(`SELECT DISTINCT prediction_market market FROM predictions WHERE prediction_market IS NOT NULL`);const out:BacktestReport[]=[];for(const r of ms)out.push(await backtestMarket(String(r.market)));return out;}
