import { query } from '../db/index.js';
export interface BacktestReport{market:string;samples:number;testSamples:number;modelBrier:number;marketBrier:number;modelLogLoss:number;marketLogLoss:number;roi:number|null;avgClv:number|null;roiCi95:[number,number]|null;clvBeatPct:number|null;edgePValue:number|null;validated:boolean;reason:string;}
const clamp=(x:number)=>Math.max(.001,Math.min(.999,x));
const ll=(p:number,y:number)=>-(y*Math.log(clamp(p))+(1-y)*Math.log(1-clamp(p)));
function rng(seed:number){let x=seed>>>0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296;};}
function boot(a:number[],seed:number):[number,number]|null{if(!a.length)return null;const r=rng(seed),m:number[]=[];for(let b=0;b<2000;b++){let s=0;for(let i=0;i<a.length;i++)s+=a[Math.floor(r()*a.length)];m.push(s/a.length);}m.sort((x,y)=>x-y);return[m[Math.floor(m.length*.025)],m[Math.floor(m.length*.975)]];}
function comb(n:number,k:number){let r=1;for(let i=1;i<=k;i++)r=r*(n-k+i)/i;return r;}
function signP(a:number[]){const x=a.filter(v=>v!==0),n=x.length;if(!n)return null;const k=x.filter(v=>v>0).length;let q=0;for(let i=0;i<=Math.min(k,n-k);i++)q+=comb(n,i)/2**n;return Math.min(1,2*q);}
export async function backtestMarket(market:string):Promise<BacktestReport>{const rows=await query<Record<string,unknown>[]>(`SELECT probability,recommended_odds,status,roi,clv_achieved FROM predictions WHERE LOWER(TRIM(prediction_market))=LOWER(TRIM(?)) AND status IN ('won','lost') ORDER BY created_at ASC`,[market]);const n=rows.length,cut=Math.floor(n*.7),test=rows.slice(cut);if(test.length<20)return{market,samples:n,testSamples:test.length,modelBrier:0,marketBrier:0,modelLogLoss:0,marketLogLoss:0,roi:null,avgClv:null,roiCi95:null,clvBeatPct:null,edgePValue:null,validated:false,reason:'Insufficient chronological holdout data.'};const y=(r:Record<string,unknown>)=>r.status==='won'?1:0;const mp=(r:Record<string,unknown>)=>Number(r.probability)/100;const qp=(r:Record<string,unknown>)=>Number(r.recommended_odds)>1?1/Number(r.recommended_odds):.5;const mb=test.reduce((s,r)=>s+(mp(r)-y(r))**2,0)/test.length,bb=test.reduce((s,r)=>s+(qp(r)-y(r))**2,0)/test.length,ml=test.reduce((s,r)=>s+ll(mp(r),y(r)),0)/test.length,bl=test.reduce((s,r)=>s+ll(qp(r),y(r)),0)/test.length;const roiA=test.filter(r=>r.roi!=null).map(r=>Number(r.roi)),clv=test.filter(r=>r.clv_achieved!=null).map(r=>Number(r.clv_achieved));const roi=roiA.length?roiA.reduce((s,x)=>s+x,0)/roiA.length:null,avgClv=clv.length?clv.reduce((s,x)=>s+x,0)/clv.length:null,ci=boot(roiA,market.length*97+11),beat=clv.length?clv.filter(x=>x>0).length/clv.length:null,p=signP(roiA);const validated=mb<=bb&&ml<=bl&&(roi??-1)>0&&(ci?ci[0]>0:false)&&(avgClv??-1)>0&&(p??1)<.05;return{market,samples:n,testSamples:test.length,modelBrier:mb,marketBrier:bb,modelLogLoss:ml,marketLogLoss:bl,roi,avgClv,roiCi95:ci,clvBeatPct:beat,edgePValue:p,validated,reason:validated?'PASS: out-of-sample model quality and positive edge are statistically supported.':'FAIL: no statistically proven durable edge; betting remains blocked.'};}
export async function backtestAll(){const ms=await query<Record<string,unknown>[]>(`SELECT DISTINCT prediction_market market FROM predictions WHERE prediction_market IS NOT NULL`);const out:BacktestReport[]=[];for(const r of ms)out.push(await backtestMarket(String(r.market)));return out;}
