import { query } from '../db/index.js';
export interface CalibrationParams{market:string;method:'platt';a:number;b:number;samples:number;brier:number;logLoss:number;ece:number;roi:number|null;avgClv:number|null;edgeValidated:boolean;updatedAt:string;}
const MIN_SAMPLES=Number(process.env.CALIBRATION_MIN_SAMPLES||50),MIN_EDGE_SAMPLES=Number(process.env.EDGE_MIN_SAMPLES||50);const cache=new Map<string,CalibrationParams>();const clamp=(x:number)=>Math.max(.001,Math.min(.999,x));const sigmoid=(z:number)=>1/(1+Math.exp(-Math.max(-35,Math.min(35,z))));const keyOf=(m:string)=>m.trim().toLowerCase().replace(/\s+/g,' ');
function fit(s:Array<{p:number;y:number}>){let a=1,b=0;for(let e=0;e<1200;e++){let ga=0,gb=0;for(const x of s){const z=Math.log(clamp(x.p)/(1-clamp(x.p))),q=sigmoid(a*z+b);ga+=(q-x.y)*z;gb+=q-x.y;}const n=s.length||1;a-=.08*ga/n;b-=.08*gb/n;if(Math.abs(ga/n)+Math.abs(gb/n)<1e-7)break;}return{a,b};}
function metrics(s:Array<{p:number;y:number}>){if(!s.length)return{brier:0,logLoss:0,ece:0};let brier=0,logLoss=0;const bins=Array.from({length:10},()=>({n:0,p:0,y:0}));for(const x of s){const p=clamp(x.p);brier+=(p-x.y)**2;logLoss-=x.y*Math.log(p)+(1-x.y)*Math.log(1-p);const i=Math.min(9,Math.floor(p*10));bins[i].n++;bins[i].p+=p;bins[i].y+=x.y;}const ece=bins.reduce((z,b)=>b.n?z+b.n/s.length*Math.abs(b.p/b.n-b.y/b.n):z,0);return{brier:brier/s.length,logLoss:logLoss/s.length,ece};}

export function applyCalibration(market:string,raw:number){const p=clamp(raw),c=cache.get(keyOf(market));return !c||c.samples<MIN_SAMPLES?p:clamp(sigmoid(c.a*Math.log(p/(1-p))+c.b));}
export function getCalibrationStatus(market:string){return cache.get(keyOf(market))||null;}
export function marketIsValidated(market:string){const c=getCalibrationStatus(market);return !!c&&c.samples>=MIN_EDGE_SAMPLES&&c.edgeValidated;}

/**
 * A market may be analyzable without being calibration-validated. Keep that state
 * visible so synthesis can distinguish "uncalibrated" from "not analyzed".
 */
export function getMarketCalibrationGate(market:string){
  const c=getCalibrationStatus(market);
  if(!c) return {state:'uncalibrated' as const,validated:false,samples:0,edgeValidated:false,reason:'No historical calibration data loaded for this exact market.'};
  if(c.samples<MIN_SAMPLES) return {state:'warming' as const,validated:false,samples:c.samples,edgeValidated:c.edgeValidated,reason:`Only ${c.samples} settled samples; ${MIN_SAMPLES} required for calibration.`};
  if(c.samples<MIN_EDGE_SAMPLES || !c.edgeValidated) return {state:'calibrated_not_validated' as const,validated:false,samples:c.samples,edgeValidated:c.edgeValidated,reason:'Calibration exists but the historical edge/backtest gate is not validated.'};
  return {state:'validated' as const,validated:true,samples:c.samples,edgeValidated:true,reason:'Exact market has passed calibration and edge validation.'};
}

export async function recalibrateMarket(market:string):Promise<CalibrationParams|null>{const key=keyOf(market);const rows=await query<Record<string,unknown>[]>(`SELECT probability,status,roi,clv_achieved FROM predictions WHERE LOWER(TRIM(prediction_market))=? AND status IN ('won','lost') AND probability IS NOT NULL ORDER BY created_at ASC`,[key]);const s=rows.map(r=>({p:Number(r.probability)/100,y:r.status==='won'?1:0}));if(s.length<MIN_SAMPLES){cache.delete(key);return null;}const{a,b}=fit(s),cal=s.map(x=>({...x,p:sigmoid(a*Math.log(clamp(x.p)/(1-clamp(x.p)))+b)})),m=metrics(cal);const rr=rows.filter(r=>r.roi!=null),cr=rows.filter(r=>r.clv_achieved!=null);const roi=rr.length?rr.reduce((z,r)=>z+Number(r.roi),0)/rr.length:null,avgClv=cr.length?cr.reduce((z,r)=>z+Number(r.clv_achieved),0)/cr.length:null;let edgeValidated=false;try{const{backtestMarket}=await import('./backtest.js');const bt=await backtestMarket(key);edgeValidated=bt.validated&&bt.testSamples>=MIN_EDGE_SAMPLES;}catch(e){console.warn('[Calibration] backtest gate unavailable',e);}const out={market:key,method:'platt' as const,a,b,samples:s.length,...m,roi,avgClv,edgeValidated,updatedAt:new Date().toISOString()};cache.set(key,out);await query(`INSERT INTO model_calibration (market,method,a,b,samples,brier,log_loss,ece,roi,avg_clv,edge_validated,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON DUPLICATE KEY UPDATE method=VALUES(method),a=VALUES(a),b=VALUES(b),samples=VALUES(samples),brier=VALUES(brier),log_loss=VALUES(log_loss),ece=VALUES(ece),roi=VALUES(roi),avg_clv=VALUES(avg_clv),edge_validated=VALUES(edge_validated),updated_at=CURRENT_TIMESTAMP`,[key,out.method,a,b,out.samples,out.brier,out.logLoss,out.ece,roi,avgClv,edgeValidated?1:0]);return out;}

export async function initCalibration(){try{const ms=await query<Record<string,unknown>[]>(`SELECT DISTINCT prediction_market market FROM predictions WHERE prediction_market IS NOT NULL`);for(const r of ms)try{await recalibrateMarket(String(r.market));}catch(e){console.warn('[Calibration] market failed',r.market,e);}console.log(`[Calibration] Loaded ${cache.size} market calibrators.`);}catch(e){console.warn('[Calibration] init skipped',e instanceof Error?e.message:String(e));}}
export async function getCalibrationReport(){return query<CalibrationParams[]>(`SELECT market,method,a,b,samples,brier,log_loss logLoss,ece,roi,avg_clv avgClv,edge_validated edgeValidated,updated_at updatedAt FROM model_calibration ORDER BY market`);}
