import { EventEmitter } from 'events';
import { v4 as uuidv4 } from 'uuid';
import { query } from '../db/index.js';
import { runOrchestrator } from './orchestrator.js';
import type { ReActStep } from './react-engine.js';
import { getAgentPreset } from './presets.js';

export type AgentJobStatus = 'queued' | 'running' | 'completed' | 'failed' | 'cancelled';
export interface AgentJobResult { success:boolean; finalAnswer:string; stepCount:number; metadata?:Record<string,unknown>; error?:string; }
interface AgentJob { id:string; sessionId:string; status:AgentJobStatus; steps:ReActStep[]; result?:AgentJobResult; predictionId?:string; error?:string; emitter:EventEmitter; promise:Promise<void>; }
const jobs=new Map<string,AgentJob>(); const MAX_MEMORY_JOBS=100;
const serialize=(v:unknown)=>{try{return JSON.stringify(v);}catch{return '{}';}};
async function persist(job:AgentJob){try{await query(`INSERT INTO agent_jobs (id,session_id,status,steps,result,prediction_id,error,updated_at) VALUES (?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON DUPLICATE KEY UPDATE status=VALUES(status),steps=VALUES(steps),result=VALUES(result),prediction_id=VALUES(prediction_id),error=VALUES(error),updated_at=CURRENT_TIMESTAMP`,[job.id,job.sessionId,job.status,serialize(job.steps),job.result?serialize(job.result):null,job.predictionId||null,job.error||null]);}catch(err){console.error('[Jobs] Persist failed:',err instanceof Error?err.message:String(err));}}
function trimMemoryJobs(){if(jobs.size<=MAX_MEMORY_JOBS)return;for(const[id,job]of jobs){if(job.status==='completed'||job.status==='failed'||job.status==='cancelled')jobs.delete(id);if(jobs.size<=MAX_MEMORY_JOBS)break;}}

async function savePrediction(job:AgentJob,result:AgentJobResult){
  if(!result.success||!result.finalAnswer||job.predictionId)return;
  const m=result.metadata||{},mc=(m.monteCarlo||{}) as Record<string,unknown>,predId=uuidv4();
  const recommendedOdds=Number(m.recommendedOdds)>1?Number(m.recommendedOdds):(Number(m.impliedProb)>0?parseFloat((1/Number(m.impliedProb)).toFixed(3)):null);
  const fixtureStr=String(m.fixture||'').slice(0,490),leagueStr=String(m.sport||'').slice(0,190),marketStr=String(m.market||'').slice(0,190),goalStr=String(m.goalStatement||'').slice(0,490);
  const stdDev=Number.isFinite(Number(mc.stdDev))?Number(mc.stdDev):null;
  await query(`INSERT INTO predictions (id,session_id,fixture,league,prediction_market,goal_statement,probability,confidence_score,star_rating,recommended_odds,expected_value,data_completeness_score,status,raw_analysis,react_trace,feature_snapshot,model_weights,monte_carlo_variance) VALUES (?,?,?,?,?,?,?,?,?,?,?,?, 'pending',?,?,?,?,?)`,[predId,job.sessionId,fixtureStr,leagueStr,marketStr,goalStr,m.probability??m.trueProb??null,m.confidence??null,m.starRating??null,recommendedOdds,m.expectedValue??null,m.dataCompletenessScore??null,result.finalAnswer,serialize(job.steps),serialize(result.metadata),serialize({agentsRun:m.agentsRun,subagentResults:m.subagentResults}),stdDev]);
  if(Number.isFinite(Number(mc.home))||Number.isFinite(Number(mc.draw))||Number.isFinite(Number(mc.away))||stdDev!==null){try{const implied=m.impliedProb??null,trueProb=m.trueProb??null,edge=trueProb!=null&&implied!=null?parseFloat((Number(trueProb)-Number(implied)).toFixed(4)):null;await query(`INSERT INTO feature_vectors (id,prediction_id,monte_carlo_home_win,monte_carlo_draw,monte_carlo_away_win,monte_carlo_std_dev,implied_prob_home,true_prob_home,value_edge_home,confidence_tier) VALUES (?,?,?,?,?,?,?,?,?,?)`,[uuidv4(),predId,mc.home??null,mc.draw??null,mc.away??null,stdDev,implied,trueProb,edge,m.starRating??null]);}catch(err){console.error('[Jobs] Save feature_vectors:',err instanceof Error?err.message:String(err));}}
  job.predictionId=predId; await persist(job); job.emitter.emit('saved',{predictionId:predId});
}

export async function createAgentJob(input:{sessionId:string;message?:string;preset?:string}){
  const internalPreset=input.preset?getAgentPreset(input.preset):null,effectiveMessage=internalPreset||input.message?.trim(); if(!effectiveMessage)throw new Error('message or preset required');
  const id=uuidv4(),job:AgentJob={id,sessionId:input.sessionId,status:'queued',steps:[],emitter:new EventEmitter(),promise:Promise.resolve()}; jobs.set(id,job);trimMemoryJobs();await persist(job);
  job.promise=(async()=>{job.status='running';await persist(job);job.emitter.emit('connected',{jobId:id,sessionId:job.sessionId,status:job.status});try{const result=await runOrchestrator(effectiveMessage,job.sessionId,async(step:ReActStep)=>{job.steps.push(step);if(job.steps.length===1||job.steps.length%3===0)await persist(job);job.emitter.emit('step',step);});job.result={success:result.success,finalAnswer:result.finalAnswer,stepCount:result.steps.length,metadata:result.metadata,error:result.error};job.status=result.success?'completed':'failed';job.error=result.error;if(result.success)await savePrediction(job,job.result);await persist(job);job.emitter.emit('complete',job.result);}catch(err){job.status='failed';job.error=err instanceof Error?err.message:String(err);job.result={success:false,finalAnswer:'',stepCount:job.steps.length,error:job.error};await persist(job);job.emitter.emit('error',{message:'Agent error. Please try again.'});job.emitter.emit('complete',job.result);}if(job.result?.finalAnswer){try{await query('INSERT INTO conversations (id,session_id,channel,role,content) VALUES (?,?,?,?,?)',[uuidv4(),job.sessionId,'web','assistant',job.result.finalAnswer]);}catch{}}trimMemoryJobs();})();
  void job.promise.catch(err=>console.error('[Jobs] Background job failure:',err)); return {jobId:id,sessionId:input.sessionId};
}
export async function getAgentJob(id:string):Promise<AgentJob|null>{const live=jobs.get(id);if(live)return live;try{const rows=await query<any[]>('SELECT id,session_id,status,steps,result,prediction_id,error FROM agent_jobs WHERE id=? LIMIT 1',[id]);const row=rows[0];if(!row)return null;const restored:AgentJob={id:row.id,sessionId:row.session_id,status:row.status,steps:typeof row.steps==='string'?JSON.parse(row.steps||'[]'):(row.steps||[]),result:row.result?(typeof row.result==='string'?JSON.parse(row.result):row.result):undefined,predictionId:row.prediction_id||undefined,error:row.error||undefined,emitter:new EventEmitter(),promise:Promise.resolve()};jobs.set(id,restored);return restored;}catch(err){console.error('[Jobs] Load failed:',err instanceof Error?err.message:String(err));return null;}}
export async function cancelAgentJob(id:string){const job=await getAgentJob(id);if(!job||(job.status!=='queued'&&job.status!=='running'))return false;job.status='cancelled';job.error='Cancelled by user';await persist(job);job.emitter.emit('error',{message:'Request cancelled.'});return true;}
export function subscribeAgentJob(job:AgentJob,handlers:{onStep:(step:ReActStep)=>void;onComplete:(result:AgentJobResult)=>void;onError:(data:{message:string})=>void;onSaved:(data:{predictionId:string})=>void}){job.emitter.on('step',handlers.onStep);job.emitter.on('complete',handlers.onComplete);job.emitter.on('error',handlers.onError);job.emitter.on('saved',handlers.onSaved);return()=>{job.emitter.off('step',handlers.onStep);job.emitter.off('complete',handlers.onComplete);job.emitter.off('error',handlers.onError);job.emitter.off('saved',handlers.onSaved);};}
