/** Deterministic market-specific scorer with calibrated edge and advanced evidence gates. */
import type { MCResult } from './monte-carlo.js';
import { applyCalibration, getCalibrationStatus, marketIsValidated } from './calibration.js';
export const ACCURACY_GATE={MIN_EV_PCT:3,MIN_DATA_COMPLETENESS:55,MIN_CONFIDENCE_FOR_MAX_STAKE:70,MIN_STAR_FOR_STANDARD_STAKE:3} as const;
export interface MarketSignals{impliedProbHome:number;impliedProbDraw?:number;impliedProbAway?:number;reverseLM:boolean;lineMovement:number;oddsDataQuality:number;openingOddsHome?:number;currentOddsHome?:number;pinnacleOdds?:number;openingOddsDraw?:number;currentOddsDraw?:number;openingOddsAway?:number;currentOddsAway?:number;selectionOdds?:number;selectionImpliedProb?:number;overround?:number;}
export interface FormSignals{xgHome:number;xgAway:number;xgConcededHome:number;xgConcededAway:number;formPtsHome:number;formPtsAway:number;h2hWinRateHome:number;formDataQuality:number;homeWinPctVenue:number;awayWinPctVenue:number;streakHome:number;streakAway:number;restDaysHome:number;restDaysAway:number;}
export interface InjurySignals{injuryIndexHome:number;injuryIndexAway:number;gtdRiskHome:number;gtdRiskAway:number;injuryDataQuality:number;absentPlayerRatingHome?:number;absentPlayerRatingAway?:number;}
export interface SentimentSignals{motivationHome:number;motivationAway:number;weatherImpact:number;refBias:number;sentimentDataQuality:number;crowdFactor?:number;}
export interface AdvancedSignals{tacticalEdge?:number;refereeRelevance?:number;lineupQualityHome?:number;lineupQualityAway?:number;marketLiquidity?:number;bookmakerDispersion?:number;modelRiskScore?:number;dataQualityScore?:number;dataQuality?:number;}
export interface ScorerInput{market:string;mcResult:MCResult;marketSignals:Partial<MarketSignals>;formSignals:Partial<FormSignals>;injurySignals:Partial<InjurySignals>;sentimentSignals:Partial<SentimentSignals>;advancedSignals?:Partial<AdvancedSignals>;targetOdds?:number;}
export interface KellyCriterion{fullKelly:number;halfKelly:number;quarterKelly:number;recommendation:string;}
export interface ScorerOutput{finalProbability:number;categoryProbabilities:{market:number;form:number;injury:number;sentiment:number;tactical:number};dataCompletenessScore:number;completenessBreakdown:Record<string,number>;appliedWeights:{market:number;form:number;injury:number;sentiment:number;tactical:number};calibrationNote:string;expectedValue:number;expectedValuePct:number;kelly:KellyCriterion;isValueBet:boolean;gateFailReason?:string;starRating:number;recommendedStake:string;}
const W={market:.30,form:.25,injury:.18,sentiment:.07,tactical:.20};
const D:any={impliedProbHome:0,reverseLM:false,lineMovement:0,oddsDataQuality:0,xgHome:0,xgAway:0,xgConcededHome:0,xgConcededAway:0,formPtsHome:0,formPtsAway:0,h2hWinRateHome:0,formDataQuality:0,homeWinPctVenue:0,awayWinPctVenue:0,streakHome:0,streakAway:0,restDaysHome:0,restDaysAway:0,injuryIndexHome:0,injuryIndexAway:0,gtdRiskHome:0,gtdRiskAway:0,injuryDataQuality:0,absentPlayerRatingHome:0,absentPlayerRatingAway:0,motivationHome:.5,motivationAway:.5,weatherImpact:0,refBias:0,sentimentDataQuality:0,crowdFactor:0,tacticalEdge:0,refereeRelevance:0,lineupQualityHome:0,lineupQualityAway:0,marketLiquidity:0,bookmakerDispersion:0,modelRiskScore:1,dataQualityScore:0,dataQuality:0};
function fill<T>(p:Partial<T>):any{return{...D,...p};}
const clamp=(x:number,a=.05,b=.95)=>Number.isFinite(x)?Math.max(a,Math.min(b,x)):(a+b)/2;
function marketProb(s:any,mc:number){let p=Number(s.selectionImpliedProb)>0?.55*mc+.45*Number(s.selectionImpliedProb):mc;if(s.pinnacleOdds>1&&s.selectionOdds===s.currentOddsHome)p=.65*p+.35*(1/s.pinnacleOdds);if(s.reverseLM)p+=.02;p+=clamp(Number(s.lineMovement)||0,-1,1)*.025;return clamp(p);}
function formProb(s:any,mc:number,m:string){let p=mc;p+=(s.formPtsHome-s.formPtsAway)/15*.06;p+=(s.homeWinPctVenue-.45)*.08;p+=(s.h2hWinRateHome-.4)*.08;p+=(s.streakHome-s.streakAway)*.01;if(Math.abs(s.restDaysHome-s.restDaysAway)>=3)p+=(s.restDaysHome-s.restDaysAway>0?.015:-.015);const ml=m.toLowerCase();if(ml.includes('btts'))p=.5+(s.xgHome+s.xgAway-2.4)*.10;else if(ml.includes('over'))p=.5+(s.xgHome+s.xgAway-2.5)*.10;else if(ml.includes('under'))p=.5-(s.xgHome+s.xgAway-2.5)*.10;return clamp(p);}
function injuryProb(s:any,mc:number){return clamp(mc+(s.injuryIndexAway-s.injuryIndexHome)*.018+(s.gtdRiskAway-s.gtdRiskHome)*.025+(Number(s.absentPlayerRatingAway)-Number(s.absentPlayerRatingHome))*.008);}
function sentimentProb(s:any,mc:number){return clamp(mc+(s.motivationHome-s.motivationAway)*.035+s.weatherImpact*.02+s.refBias*.025+(s.crowdFactor||0)*.01);}
function tacticalProb(s:any,mc:number){const lineup=(Number(s.lineupQualityHome)-Number(s.lineupQualityAway))*.008;return clamp(mc+Number(s.tacticalEdge||0)+lineup);}
export function calcKelly(p:number,odds:number):KellyCriterion{if(!(odds>1)||!(p>0&&p<1))return{fullKelly:0,halfKelly:0,quarterKelly:0,recommendation:'NO BET — invalid price/probability'};const b=odds-1,k=Math.max(0,(b*p-(1-p))/b);return{fullKelly:Math.round(k*1000)/10,halfKelly:Math.round(k*500)/10,quarterKelly:Math.round(k*250)/10,recommendation:k<=0?'NO BET — negative edge':`${Math.min(k*50,5).toFixed(1)}% bankroll (half-Kelly, capped at 5%)`};}
export function removeOverround(decimalOdds:number,estimatedMargin=.05){if(decimalOdds<=1)return 0;return Math.min(.95,(1/decimalOdds)/(1+Math.max(0,estimatedMargin)));}
function completeness(ms:any,fs:any,is_:any,ss:any,as:any){const b={market:clamp(ms.oddsDataQuality,0,1)*100,form:clamp(fs.formDataQuality,0,1)*100,injury:clamp(is_.injuryDataQuality,0,1)*100,sentiment:clamp(ss.sentimentDataQuality,0,1)*100,tactical:clamp(as.dataQuality||0,0,1)*100};const w={market:.25,form:.20,injury:.15,sentiment:.10,tactical:.10,advanced:.20};const advanced=Math.max(0,(as.marketLiquidity||0)+((as.dataQualityScore||0))+(1-(as.modelRiskScore??1)))/3*100;return{score:Math.round((b.market*w.market+b.form*w.form+b.injury*w.injury+b.sentiment*w.sentiment+b.tactical*w.tactical+advanced*w.advanced)/10)/10,breakdown:{...b,advanced:Math.round(advanced)}};}
function stars(ev:number,c:number){const e=ev*Math.min(1,c/70);if(e>=15&&c>=70)return{stars:5,stake:'MAX'};if(e>=10)return{stars:4,stake:'CONFIDENT'};if(e>=5)return{stars:3,stake:'STANDARD'};if(e>=2)return{stars:2,stake:'SMALL'};return{stars:1,stake:e>=0?'MONITOR':'SKIP'};}
function getMC(mc:MCResult,m:string){const x=m.toLowerCase();if(x.includes('draw'))return mc.draw;if(x.includes('away'))return mc.awayWin;if(x.includes('btts')||x.includes('both teams'))return mc.btts;if(x.includes('over 3.5'))return mc.over35;if(x.includes('under 3.5'))return mc.under35;if(x.includes('over 2.5')||x.includes('over'))return mc.over25;if(x.includes('under 2.5')||x.includes('under'))return mc.under25;if(x.includes('dnb')&&x.includes('away'))return mc.dnbAway;if(x.includes('dnb'))return mc.dnbHome;if(x.includes('asian')||x.includes('ah'))return x.includes('away')?mc.ahAway05:mc.ahHome05;return mc.homeWin;}
export function score(input:ScorerInput):ScorerOutput{const ms=fill<MarketSignals>(input.marketSignals),fs=fill<FormSignals>(input.formSignals),is_=fill<InjurySignals>(input.injurySignals),ss=fill<SentimentSignals>(input.sentimentSignals),as=fill<AdvancedSignals>(input.advancedSignals||{});const mc=getMC(input.mcResult,input.market);const cats={market:marketProb(ms,mc),form:formProb(fs,mc,input.market),injury:injuryProb(is_,mc),sentiment:sentimentProb(ss,mc),tactical:tacticalProb(as,mc)};const rawFinal=clamp(cats.market*W.market+cats.form*W.form+cats.injury*W.injury+cats.sentiment*W.sentiment+cats.tactical*W.tactical);const finalProbability=applyCalibration(input.market,rawFinal);const comp=completeness(ms,fs,is_,ss,as);const odds=input.targetOdds&&input.targetOdds>1?input.targetOdds:ms.selectionOdds&&ms.selectionOdds>1?ms.selectionOdds:0;const ev=odds>1?finalProbability*odds-1:0;const kelly=calcKelly(finalProbability,odds);const st=stars(ev*100,comp.score);const cal=getCalibrationStatus(input.market);const validated=marketIsValidated(input.market);const risk=Number(as.modelRiskScore??1);let isValue=validated&&odds>1&&ev*100>=ACCURACY_GATE.MIN_EV_PCT&&comp.score>=ACCURACY_GATE.MIN_DATA_COMPLETENESS&&risk<=.65;let reason:string|undefined;if(!validated)reason=cal?`Market edge not statistically validated: n=${cal.samples}, ROI=${cal.roi===null?'n/a':(cal.roi*100).toFixed(2)+'%'}, CLV=${cal.avgClv===null?'n/a':cal.avgClv.toFixed(4)}`:`No market-specific calibration/backtest available for ${input.market}`;else if(!(odds>1))reason='No verified odds for the requested selection';else if(ev*100<ACCURACY_GATE.MIN_EV_PCT)reason=`EV ${(ev*100).toFixed(1)}% < minimum ${ACCURACY_GATE.MIN_EV_PCT}%`;else if(comp.score<ACCURACY_GATE.MIN_DATA_COMPLETENESS)reason=`Data completeness ${comp.score.toFixed(0)}% < minimum ${ACCURACY_GATE.MIN_DATA_COMPLETENESS}%`;else if(risk>.65)reason=`Model-risk score ${(risk*100).toFixed(0)}% exceeds safety limit`;const note=`Target ${input.market} | raw ${(rawFinal*100).toFixed(1)}% | calibrated ${(finalProbability*100).toFixed(1)}% | odds ${odds>1?odds.toFixed(2):'UNVERIFIED'} | EV ${(ev*100).toFixed(2)}% | data ${comp.score}% | risk ${(risk*100).toFixed(0)}% | calibration ${cal?`n=${cal.samples},ECE=${cal.ece.toFixed(3)}`:'NONE'} | edge gate ${validated?'PASS':'FAIL'}`;return{finalProbability,categoryProbabilities:cats,dataCompletenessScore:comp.score,completenessBreakdown:comp.breakdown,appliedWeights:W,calibrationNote:note,expectedValue:ev,expectedValuePct:ev*100,kelly,isValueBet:isValue,gateFailReason:reason,starRating:st.stars,recommendedStake:isValue?st.stake:'SKIP'};}
