import { query, pool } from './index.js';

export async function initSchema() {
  console.log('[DB] Initializing Aiven MySQL schema...');
  await query(`CREATE TABLE IF NOT EXISTS jobs_state (job_id VARCHAR(255) PRIMARY KEY,status VARCHAR(50) NOT NULL DEFAULT 'pending',current_checkpoint TEXT,last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`);
  await query(`CREATE TABLE IF NOT EXISTS predictions (id VARCHAR(36) PRIMARY KEY,session_id VARCHAR(255),event_date DATE,sport VARCHAR(100) DEFAULT 'football',fixture VARCHAR(500) NOT NULL,league VARCHAR(255),prediction_market VARCHAR(500) NOT NULL,goal_statement TEXT,probability DECIMAL(5,2),confidence_score DECIMAL(5,2),star_rating TINYINT DEFAULT 0,recommended_odds DECIMAL(8,3),expected_value DECIMAL(8,4),closing_line_value DECIMAL(8,4),status VARCHAR(50) NOT NULL DEFAULT 'pending',raw_analysis LONGTEXT,react_trace JSON,feature_snapshot JSON,model_weights JSON,monte_carlo_variance DECIMAL(8,4),closing_odds DECIMAL(8,3),actual_result VARCHAR(100),clv_achieved DECIMAL(8,4),roi DECIMAL(8,4),data_completeness_score DECIMAL(5,1),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_status(status),INDEX idx_created(created_at),INDEX idx_market_date(prediction_market,event_date))`);
  await query(`CREATE TABLE IF NOT EXISTS feature_vectors (id VARCHAR(36) PRIMARY KEY,prediction_id VARCHAR(36),odds_data JSON,injuries_json JSON,player_data JSON,monte_carlo_home_win DECIMAL(5,4),monte_carlo_draw DECIMAL(5,4),monte_carlo_away_win DECIMAL(5,4),monte_carlo_std_dev DECIMAL(6,4),reverse_line_movement TINYINT(1) DEFAULT 0,value_edge_home DECIMAL(6,4),public_betting_pct DECIMAL(5,2),handle_pct DECIMAL(5,2),line_delta DECIMAL(6,3),confidence_tier TINYINT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(prediction_id) REFERENCES predictions(id) ON DELETE CASCADE)`);
  await query(`CREATE TABLE IF NOT EXISTS conversations (id VARCHAR(36) PRIMARY KEY,session_id VARCHAR(255) NOT NULL,channel VARCHAR(50) DEFAULT 'web',role VARCHAR(20) NOT NULL,content LONGTEXT NOT NULL,metadata JSON,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX idx_session(session_id,created_at))`);
  await query(`CREATE TABLE IF NOT EXISTS booking_log (id VARCHAR(36) PRIMARY KEY,prediction_id VARCHAR(36),platform VARCHAR(50) NOT NULL,fixture VARCHAR(500) NOT NULL,market VARCHAR(500),selection VARCHAR(500),odds_obtained DECIMAL(8,3),stake_amount DECIMAL(10,2),potential_return DECIMAL(10,2),bet_id VARCHAR(255),betslip_ref VARCHAR(255),confirmation_text TEXT,success TINYINT(1) DEFAULT 0,error_msg TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX idx_prediction(prediction_id),INDEX idx_created(created_at))`);
  for(const [col,def] of [['closing_odds','DECIMAL(8,3)'],['actual_result','VARCHAR(100)'],['clv_achieved','DECIMAL(8,4)'],['roi','DECIMAL(8,4)'],['data_completeness_score','DECIMAL(5,1)']] as [string,string][])try{await pool.execute(`ALTER TABLE predictions ADD COLUMN ${col} ${def}`);}catch(e){if((e as {code?:string}).code!=='ER_DUP_FIELDNAME')throw e;}
  await query(`CREATE TABLE IF NOT EXISTS model_feedback (id VARCHAR(36) PRIMARY KEY,prediction_id VARCHAR(36),feature_weights_before JSON,feature_weights_after JSON,clv_achieved DECIMAL(6,4),accuracy_delta DECIMAL(6,4),correction_applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)`);
  await query(`CREATE TABLE IF NOT EXISTS model_calibration (market VARCHAR(500) PRIMARY KEY,method VARCHAR(20) NOT NULL,a DOUBLE NOT NULL,b DOUBLE NOT NULL,samples INT NOT NULL,brier DOUBLE NOT NULL,log_loss DOUBLE NOT NULL,ece DOUBLE NOT NULL,roi DOUBLE NULL,avg_clv DOUBLE NULL,edge_validated TINYINT(1) NOT NULL DEFAULT 0,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`);
  console.log('[DB] Schema ready — calibration/backtest tables initialized.');
}
